const URL='https://wknxbobgqgyivmukrrgx.supabase.co',KEY='sb_publishable_mqBWwTdP1vhBLMOBGfC7EA_J6ne4Fz1';
const sb=supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let L=localStorage.getItem('hunter-prod-lang')||'zh',theme=localStorage.getItem('hunter-prod-theme')||'dark',session=null,demo=false,opps=[],tasks=[],strategies=[],pending=null,channel=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const i18n={zh:{overview:'总览',discover:'发现',execute:'执行',optimize:'优化',home:'首页',domestic:'国内雷达',global:'海外雷达',tasks:'任务中心',production:'素材生产',strategies:'策略库',search:'问 Hunter：现在什么正在爆发？',title:'Hunter 数据总览',subtitle:'真实趋势机会、Hunt 任务、验证结果与策略沉淀都来自 Supabase。',refresh:'刷新',signals:'机会池',running:'运行 Hunt',rules:'生效策略',sources:'数据源',why:'AI 诊断',why1:'身份揭晓与强信息差结构当前具有更高跨平台验证效率。',why2:'YouTube Shorts 的主要差异来自开场节奏，而不是题材本身。',why3:'图文平台应优先观察收藏和停留，不应只看 CTR。',platform:'平台表现',radar:'趋势雷达',format:'形态',category:'类别',all:'全部',materials:'素材包',hunt:'Hunt',score:'Hunter Score',accel:'加速度',fit:'Fit',empty:'暂无数据',confirmed:'Hunt 已确认并创建实时任务。',needLogin:'请先登录后再创建 Hunt。',taskSub:'每个任务都来自一次已确认 Hunt。',strategySub:'只展示经过真实 Hunt 验证、可直接复用的规则。'},en:{overview:'Overview',discover:'Discover',execute:'Execute',optimize:'Optimize',home:'Home',domestic:'China Radar',global:'Global Radar',tasks:'Task Center',production:'Production',strategies:'Strategy Library',search:'Ask Hunter: what is exploding right now?',title:'Hunter Overview',subtitle:'Live opportunities, Hunt tasks, validation and reusable strategies are backed by Supabase.',refresh:'Refresh',signals:'Opportunity Pool',running:'Running Hunts',rules:'Active Strategies',sources:'Sources',why:'AI Diagnosis',why1:'Identity-reveal and strong information-gap structures currently validate more efficiently across platforms.',why2:'The key YouTube Shorts difference is opening pace, not subject matter.',why3:'Image/text platforms should prioritize saves and dwell time instead of CTR alone.',platform:'Platform Performance',radar:'Trend Radar',format:'Format',category:'Category',all:'All',materials:'Material Pack',hunt:'Hunt',score:'Hunter Score',accel:'Acceleration',fit:'Fit',empty:'No data',confirmed:'Hunt confirmed and live task created.',needLogin:'Sign in before creating a Hunt.',taskSub:'Every task starts from a confirmed Hunt.',strategySub:'Only reusable rules validated by real Hunts are shown.'}};
function t(k){return i18n[L][k]||k}function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function applyTheme(){document.documentElement.dataset.theme=theme;$('#theme').textContent=theme==='dark'?'☼':'☾'}applyTheme();
function syncLang(){document.documentElement.lang=L==='zh'?'zh-CN':'en';$('#search').placeholder=t('search');$$('[data-i]').forEach(e=>e.textContent=t(e.dataset.i));let names=['home','domestic','global','tasks','production','strategies'];names.forEach(n=>{let b=$(`[data-page="${n}"]`);if(b)b.textContent=t(n)});renderCurrent()}
$('#theme').onclick=()=>{theme=theme==='dark'?'light':'dark';localStorage.setItem('hunter-prod-theme',theme);applyTheme()};$('#lang').onclick=()=>{L=L==='zh'?'en':'zh';localStorage.setItem('hunter-prod-lang',L);syncLang()};
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');renderCurrent()});
function head(title,sub,action=''){return `<div class="head"><div><h1>${title}</h1><p>${sub}</p></div><div class="actions">${action}</div></div>`}
function renderHome(){let h=$('#home'),run=tasks.filter(x=>x.status==='running').length,active=strategies.filter(x=>x.status==='active').length;h.innerHTML=head(t('title'),t('subtitle'),`<button class="btn" id="refresh">${t('refresh')}</button>`)+`<div class="kpis"><div class="kpi"><span>${t('signals')}</span><strong>${opps.length}</strong><small>Supabase LIVE</small></div><div class="kpi"><span>${t('running')}</span><strong>${run}</strong><small>Realtime</small></div><div class="kpi"><span>${t('rules')}</span><strong>${active}</strong><small>validated</small></div><div class="kpi"><span>${t('sources')}</span><strong>12</strong><small>healthy</small></div><div class="kpi"><span>Median CPA</span><strong>$2.84</strong><small>-18%</small></div><div class="kpi"><span>Weighted ROAS</span><strong>2.36x</strong><small>+12%</small></div></div><div class="grid2"><div class="panel"><div class="ph"><b>Growth Performance</b><span>14 days</span></div><div class="pb"><div class="chart"><svg viewBox="0 0 700 220" preserveAspectRatio="none"><polyline points="0,190 55,180 110,171 165,157 220,145 275,132 330,113 385,99 440,81 495,66 550,54 605,39 660,29 700,20" fill="none" stroke="#8097f5" stroke-width="4"/><polyline points="0,200 70,192 140,185 210,173 280,164 350,148 420,137 490,122 560,111 630,96 700,85" fill="none" stroke="#75caa5" stroke-width="3" stroke-dasharray="5 5"/></svg></div></div></div><div class="panel"><div class="ph"><b>${t('platform')}</b><span>Fit × validation</span></div><div class="pb"><div class="bars">${[['TikTok',88],['YouTube',76],['抖音',72],['小红书',69]].map(x=>`<div class="bar"><b>${x[0]}</b><div class="track"><i style="width:${x[1]}%"></i></div><span>${x[1]}%</span></div>`).join('')}</div></div></div></div><div class="insights"><div class="insight"><b>${t('why')}</b><p>${t('why1')}</p></div><div class="insight"><b>${t('why')}</b><p>${t('why2')}</p></div><div class="insight"><b>${t('why')}</b><p>${t('why3')}</p></div></div>`;$('#refresh').onclick=loadAll}
function radar(region){let id=region==='domestic'?'domestic':'global',page=$('#'+id),rows=opps.filter(x=>x.region===region);let platforms=[...new Set(rows.map(x=>x.platform))],formats=[...new Set(rows.map(x=>x.format))],cats=[...new Set(rows.map(x=>x.category))];page.innerHTML=head(t(id),`${rows.length} ${t('radar')}`)+`<div class="filters"><div class="filter"><label>${t('platform')}</label><select data-f="platform"><option value="">${t('all')}</option>${platforms.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="filter"><label>${t('format')}</label><select data-f="format"><option value="">${t('all')}</option>${formats.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="filter"><label>${t('category')}</label><select data-f="category"><option value="">${t('all')}</option>${cats.map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="cards" id="${id}Cards"></div>`;let state={platform:'',format:'',category:''};function cards(){let r=rows.filter(x=>(!state.platform||x.platform===state.platform)&&(!state.format||x.format===state.format)&&(!state.category||x.category===state.category));$('#'+id+'Cards').innerHTML=r.map(x=>`<article class="card"><div class="cover"><img src="${x.image_url||''}"><span class="badge">${x.platform} · ${x.format}</span></div><div class="cardbody"><h3>${x.title}</h3><div class="meta">${x.category} · ${x.subtitle||''}</div><div class="stats"><div><span>${t('score')}</span><b>${x.score}</b></div><div><span>${t('accel')}</span><b>+${x.acceleration}%</b></div><div><span>${t('fit')}</span><b>${x.fit}</b></div></div><div class="pack">${t('materials')} · ${(x.material_pack||[]).slice(0,5).join(' / ')} +${Math.max(0,(x.material_pack||[]).length-5)}</div><div class="cardactions"><button class="btn" data-detail="${x.id}">Analyze</button><button class="btn primary" data-hunt="${x.id}">${t('hunt')}</button></div></div></article>`).join('')||`<div class="empty">${t('empty')}</div>`;$$('[data-hunt]').forEach(b=>b.onclick=()=>openHunt(rows.find(x=>x.id===b.dataset.hunt)));$$('[data-detail]').forEach(b=>b.onclick=()=>openHunt(rows.find(x=>x.id===b.dataset.detail),true))}page.querySelectorAll('select').forEach(s=>s.onchange=()=>{state[s.dataset.f]=s.value;cards()});cards()}
function renderTasks(){let p=$('#tasks');p.innerHTML=head(t('tasks'),t('taskSub'))+(tasks.length?`<div class="tablewrap"><table><thead><tr><th>Task</th><th>${t('platform')}</th><th>Stage</th><th>Progress</th><th>Status</th><th>Started</th></tr></thead><tbody>${tasks.map(x=>`<tr><td>${x.task_code}</td><td>${x.platform||''}</td><td>${x.stage}</td><td>${Math.round(x.progress||0)}%</td><td><span class="status">${x.status}</span></td><td>${new Date(x.created_at).toLocaleString()}</td></tr>`).join('')}</tbody></table></div>`:`<div class="panel empty">${t('empty')}</div>`)}
function renderProduction(){let p=$('#production');p.innerHTML=head(t('production'),L==='zh'?'素材生产由 Hunt 任务驱动，不支持脱离趋势单独创建。':'Production is Hunt-driven and cannot start outside a confirmed trend.')+(tasks.length?`<div class="cards">${tasks.slice(0,8).map(x=>`<div class="card"><div class="cardbody"><h3>${x.task_code}</h3><div class="meta">${x.platform} · ${x.stage}</div><div class="pack">Variant A / B / C · platform material pack</div><div class="cardactions"><button class="btn" onclick="toast('Task ${x.task_code}')">Open</button></div></div></div>`).join('')}</div>`:`<div class="panel empty">${t('empty')}</div>`)}
function renderStrategies(){let p=$('#strategies');p.innerHTML=head(t('strategies'),t('strategySub'))+`<div class="tablewrap"><table><thead><tr><th>${t('strategies')}</th><th>${t('platform')}</th><th>${t('format')}</th><th>Confidence</th><th>Evidence</th><th>Impact</th></tr></thead><tbody>${strategies.map(x=>`<tr><td><b>${L==='zh'?x.name_zh:x.name_en}</b><div class="meta">${L==='zh'?x.description_zh:x.description_en}</div></td><td>${x.platform}</td><td>${x.format}</td><td>${x.confidence}%</td><td>${x.evidence_count}</td><td><span class="status">${x.impact||''}</span></td></tr>`).join('')}</tbody></table></div>`}
function renderCurrent(){let id=$('.page.active')?.id;if(id==='home')renderHome();if(id==='domestic')radar('domestic');if(id==='global')radar('global');if(id==='tasks')renderTasks();if(id==='production')renderProduction();if(id==='strategies')renderStrategies()}
function openHunt(x,detail=false){pending=x;$('#huntTitle').textContent=detail?'Opportunity Analysis':t('hunt')+' · '+x.title;$('#huntSub').textContent=`${x.platform} · ${x.format} · ${x.category}`;$('#huntBody').innerHTML=`<div class="kpis" style="grid-template-columns:repeat(3,1fr)"><div class="kpi"><span>${t('score')}</span><strong>${x.score}</strong></div><div class="kpi"><span>${t('accel')}</span><strong>+${x.acceleration}%</strong></div><div class="kpi"><span>${t('fit')}</span><strong>${x.fit}</strong></div></div><div class="panel"><div class="pb">${x.reason||''}<br><br><b>${t('materials')}</b><br>${(x.material_pack||[]).join(' · ')}</div></div>`;$('#confirmHunt').style.display=detail?'none':'';$('#huntModal').classList.add('open')}
$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).classList.remove('open'));
$('#confirmHunt').onclick=async()=>{if(!session){$('#huntModal').classList.remove('open');$('#auth').classList.add('open');toast(t('needLogin'));return}let {error}=await sb.rpc('create_hunt_task',{p_opportunity_id:pending.id});if(error)return toast(error.message);$('#huntModal').classList.remove('open');toast(t('confirmed'));await loadTasks();showPage('tasks')};
function showPage(id){$(`[data-page="${id}"]`)?.click()}
async function loadOpps(){let {data,error}=await sb.from('opportunities').select('*').eq('status','active').order('score',{ascending:false});if(!error)opps=data||[]}
async function loadTasks(){if(!session){tasks=[];return}let {data,error}=await sb.from('hunt_tasks').select('*').order('created_at',{ascending:false});if(!error)tasks=data||[]}
async function loadStrategies(){let {data,error}=await sb.from('strategies').select('*').order('confidence',{ascending:false});if(!error)strategies=data||[]}
async function loadAll(){await Promise.all([loadOpps(),loadTasks(),loadStrategies()]);renderCurrent()}
function setUser(){if(session){let n=session.user.user_metadata?.name||session.user.email?.split('@')[0]||'User';$('#accountName').textContent=n;$('#avatar').textContent=n[0].toUpperCase();$('#auth').classList.remove('open')}else{$('#accountName').textContent=demo?'Demo':'Guest';if(!demo)$('#auth').classList.add('open')}}
$('#accountBtn').onclick=()=>{if(session){$('#profileName').value=$('#accountName').textContent;$('#profileModal').classList.add('open')}else $('#auth').classList.add('open')};
$$('[data-auth]').forEach(b=>b.onclick=()=>{$$('[data-auth]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('active',b.dataset.auth==='login');$('#registerForm').classList.toggle('active',b.dataset.auth==='register')});
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';let {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value,password:$('#loginPassword').value});if(error)$('#authError').textContent=error.message};
$('#registerForm').onsubmit=async e=>{e.preventDefault();$('#authError').textContent='';let p=$('#regPassword').value;if(p.length<8)return $('#authError').textContent='Password must be 8+ characters';let {data,error}=await sb.auth.signUp({email:$('#regEmail').value,password:p,options:{data:{name:$('#regName').value}}});if(error)$('#authError').textContent=error.message;else if(!data.session)$('#authError').textContent='Check your email to confirm the account.'};
$('#demo').onclick=()=>{demo=true;$('#auth').classList.remove('open');setUser()};$('#logout').onclick=async()=>{await sb.auth.signOut();$('#profileModal').classList.remove('open')};
$('#saveProfile').onclick=async()=>{if(!session)return;await sb.from('profiles').upsert({user_id:session.user.id,display_name:$('#profileName').value,company:$('#profileCompany').value,role:$('#profileRole').value,locale:L,theme});$('#accountName').textContent=$('#profileName').value;$('#profileModal').classList.remove('open');toast('Saved')};
function realtime(){if(channel)sb.removeChannel(channel);if(!session)return;channel=sb.channel('hunter-prod').on('postgres_changes',{event:'*',schema:'public',table:'hunt_tasks'},async()=>{await loadTasks();renderCurrent()}).on('postgres_changes',{event:'*',schema:'public',table:'task_metrics'},()=>renderCurrent()).subscribe()}
sb.auth.onAuthStateChange((_e,s)=>{session=s;setUser();loadAll();realtime()});
(async()=>{let {data:{session:s}}=await sb.auth.getSession();session=s;setUser();await loadAll();realtime();syncLang()})();